from typing import Protocol, TypeVar, Generic

T_Element = TypeVar("T_Element")


class XMLBackend(Protocol, Generic[T_Element]):
  def make_elem(self, tag: str) -> T_Element: ...
  def set_attr(self, element: T_Element, key: str, val: str) -> None: ...
  def set_text(self, element: T_Element, text: str | None) -> None: ...
  def append(self, parent: T_Element, child: T_Element) -> None: ...
